//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dtc21h4801030029.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiayChiTiet1
    {
        public int idTT { get; set; }
        public string TenGiay { get; set; }
        public string Mau { get; set; }
        public int Soluong { get; set; }
        public int idGiay { get; set; }
    
        public virtual TTGiay TTGiay { get; set; }
    }
}
