//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dtc21h4801030029.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTGiay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TTGiay()
        {
            this.GiayChiTiet1 = new HashSet<GiayChiTiet1>();
        }
    
        public int idGiay { get; set; }
        public string LoaiGiay { get; set; }
        public string ThongTin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiayChiTiet1> GiayChiTiet1 { get; set; }
    }
}
